services:
  api:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: api-login
    ports:
     - "8093:8093"
    environment:
      SPRING_DATASOURCE_URL: jdbc:mysql://mysql:3306/bd_apilogin
      SPRING_DATASOURCE_USERNAME: user_coti
      SPRING_DATASOURCE_PASSWORD: coti
    depends_on:
        - mysql

  mysql:
    image: mysql:latest
    environment:
      MYSQL_USER: user_coti
      MYSQL_ROOT_PASSWORD: coti
      MYSQL_PASSWORD: coti
      MYSQL_DATABASE: bd_apilogin
    ports:
      - "3306:3306"

networks:
  default:
    driver: bridge